<a href="https://colab.research.google.com/github/PvrpleJade/Numerical-Methods/blob/main/Matrix_Algebra.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Matrix and its Operation

In [8]:
import numpy as np
a = np.array([1,2,3]) #This is 1x3 array
print (a)
print (a.shape)

[1 2 3]
(3,)


In [19]:
import numpy as np
b = np.array([[1,2,3],[4,5,6]]) #This is an example of 2x3 array
print (b)
print (b.shape)
b[0,0] = 7
b[1,2] = 3
print (b)

[[1 2 3]
 [4 5 6]]
(2, 3)
[[7 2 3]
 [4 5 3]]


In [21]:
import numpy as np
c = np.array ([[1,2,3],[4,5,6],[7,8,9]])#this is an example of square matrix
print (c)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [26]:
import numpy as np
d = np.full((2,2),4)
print (d)

[[4 4]
 [4 4]]


In [33]:
import numpy as np
e = np.eye(2)
print (e)

[[1. 0.]
 [0. 1.]]


In [42]:
import numpy as np
e = np. diagonal([[1,2,3],[4,5,6],[7,8,9]])
print (e)



[1 5 9]


In [44]:
import numpy as np
f = np.empty((0,10))
print (f)

[]


In [50]:
import numpy as np
g = np.zeros((2,2))
print (g)

[[0. 0.]
 [0. 0.]]


In [56]:
import numpy as np
e = np.eye(2)
g = np.zeros((2,2))
print(e)
print(g)
print (e+g)
print(e-g)


[[1. 0.]
 [0. 1.]]
[[0. 0.]
 [0. 0.]]
[[1. 0.]
 [0. 1.]]
[[1. 0.]
 [0. 1.]]
