<a href="https://colab.research.google.com/github/PvrpleJade/Numerical-Methods/blob/main/Python_Exercise_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Matrix and its Operation
###Test Content

###Create a NumPy program that performs the operations of the given matrices:

#####1.sum = A +B
#####2.difference1 = B - A
#####3.difference2 = A - B


#SUM

In [9]:
import numpy as np
a = np.array([[-5,0],[4,1]])
print (a)
b = np.array([[6,-3],[2,3]])
print (b)
sum = a+b
diff1 = b-a
diff2 = a-b
print (sum)



[[-5  0]
 [ 4  1]]
[[ 6 -3]
 [ 2  3]]
[[ 1 -3]
 [ 6  4]]


#Difference 1

In [10]:
a = np.array([[-5,0],[4,1]])
print (a)
b = np.array([[6,-3],[2,3]])
print (b)
print (diff1)

[[-5  0]
 [ 4  1]]
[[ 6 -3]
 [ 2  3]]
[[11 -3]
 [-2  2]]


#Difference 2

In [11]:
a = np.array([[-5,0],[4,1]])
print (a)
b = np.array([[6,-3],[2,3]])
print (b)
print (diff2)

[[-5  0]
 [ 4  1]]
[[ 6 -3]
 [ 2  3]]
[[-11   3]
 [  2  -2]]
