<a href="https://colab.research.google.com/github/PvrpleJade/Numerical-Methods/blob/main/Python_Exercise_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Matrix and its Operation

In [6]:
import numpy as np
a = np.array([[-5,0],[4,1]])
print (a)
b = np.array([[6,-3],[2,3]])
print (b)
sum = a+b
diff1 = b-a
diff2 = a-b
print (sum)
print (diff1)
print (diff2)



[[-5  0]
 [ 4  1]]
[[ 6 -3]
 [ 2  3]]
[[ 1 -3]
 [ 6  4]]
[[11 -3]
 [-2  2]]
[[-11   3]
 [  2  -2]]
